.apex/unpackaged/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/unpackaged/classes/AccountHandler.cls
public class AccountHandler {
    public static void onAfterUpdate(List <Order__c> orders)
    {
       Set <Id> parentId = Utils.getParentIds(orders,'Account__c');
        Map <Id, Account> relatedAccount = new Map<Id, Account>([SELECT Total_Income__c, Last_Payment_Date__c
                                                    FROM Account 
                                                    WHERE id in :parentId]);
        AggregateResult [] aggregateResults = [SELECT Sum(Payment_Amount__c), Account__c
                                               FROM Order__c 
                                               WHERE Account__c in :parentId 
                                               GROUP BY Account__c];
        for(AggregateResult aggRes : aggregateResults)
        {
            
        }
        
    }
       
  
}