unpackaged/objects/Mix__c.object
<CustomObject>
    <description>A custom collection of tracks for a customer that will be pressed onto vinyl.</description>
    <fields>
        <fullName>Primary_Genre__c</fullName>
        <description>Primary genre of the mix.</description>
        <label>Primary Genre</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Genre__c</fullName>
        <description>Secondary genre of the mix.</description>
        <label>Secondary Genre</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Song__c.object
<CustomObject>
    <description>An instance of a song.</description>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/unpackaged/classes/MixBuilderController.cls
public class MixBuilderController {
	private Id id;
	private Mix__c mix {get;set;}

	 public MixBuilderController ()
	{
		System.debug('ds');
		id = ApexPages.currentPage().getParameters().get('Id');
		mix = (id==null)? new Mix__c(): [
			SELECT Name, (
					SELECT name,Song__c
					FROM Tracks__r), Primary_Genre__c, Secondary_Genre__c
			FROM Mix__c
			Where Id = :id
			  Limit 1];

		System.debug(mix);
	}

	public List<Song__c> getSongs ()
	{
		System.debug( SongService.getRelatedSongs(mix.Tracks__r));
		return  SongService.getRelatedSongs(mix.Tracks__r);

	}
}