unpackaged/objects/Mix__c.object
<CustomObject>
    <description>A custom collection of tracks for a customer that will be pressed onto vinyl.</description>
    <fields>
        <fullName>Primary_Genre__c</fullName>
        <description>Primary genre of the mix.</description>
        <label>Primary Genre</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Genre__c</fullName>
        <description>Secondary genre of the mix.</description>
        <label>Secondary Genre</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/objects/Song__c.object
<CustomObject>
    <description>An instance of a song.</description>
    <fields>
        <fullName>Genre__c</fullName>
        <description>Genre of the song.</description>
        <label>Genre</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rock</fullName>
                </value>
                <value>
                    <fullName>Rap</fullName>
                </value>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Indy</fullName>
                </value>
                <value>
                    <fullName>Jazz</fullName>
                </value>
                <value>
                    <fullName>Latin</fullName>
                </value>
                <value>
                    <fullName>Electronic</fullName>
                </value>
                <value>
                    <fullName>Folk</fullName>
                </value>
                <value>
                    <fullName>Pop</fullName>
                </value>
                <value>
                    <fullName>Hip hop</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/unpackaged/classes/MixService.cls
/**
 * Created by HP on 22.11.2017.
 */
public class MixService
{
    public static void setPrimaryAndSecondaryGenre (List<Mix__c> newValues)
    {
        List<Mix__c> mixesToUpdate = new List<Mix__c>();
        for (Mix__c mix : newValues)
        {
            if (mix.Tracks__r.size() > 0)
            {
                List<String> currMaxGenres =getPrimeAndSecGenre(mix);
                mix.Primary_Genre__c = currMaxGenres.get(0);
                mix.Secondary_Genre__c = currMaxGenres.get(1);
                mixesToUpdate.add(mix);
            }
        }
        update mixesToUpdate;
    }

    private static Map<String, Integer> getNumberOfEachGenre (Mix__c mix)
	{
			List<String> primaryAndSecondaryGenre = new List<String>();
			Map<String, Integer> numOfEachGenre = new Map<String, Integer>();
			String maxUsedGenre;
			String secondMaxUsedGenre;
			Integer numOfMaxGenre = 0;
			Integer numOfSecondMaxUsedGenre = 0;
			Map<Id, Song__c> usedSongs = SongService.getAppropriateSongs(mix.Tracks__r);

			for (Track__c track : mix.Tracks__r)
            {
					Song__c currentSong = usedSongs.get(track.Song__c);
					String currentGenre = currentSong.Genre__c;
					Integer numOfCurrGenre = numOfEachGenre.get(currentGenre);
					if (numOfCurrGenre == null)
					{
						numOfCurrGenre = 1;
						numOfEachGenre.put(currentGenre, numOfCurrGenre);

					} else
					{
						numOfCurrGenre++;
						numOfEachGenre.put(currentGenre, numOfCurrGenre);
					}
					System.debug(numOfCurrGenre + '' + currentGenre);
			}
			return numOfEachGenre;
    }

	private static List <String> getPrimeAndSecGenre(Mix__c mix)
    {
		String primeGenre;
		Integer primeNumber = 0;
		String secGenre;
		Integer secNumber = 0;
		Map <String,Integer> numOfEachGenre = getNumberOfEachGenre(mix);
		for (String currGenre : numOfEachGenre.keySet())
        {
			Integer currNumber = numOfEachGenre.get(currGenre);
			if(primeNumber < currNumber)
            {
				secNumber = primeNumber;
				secGenre = primeGenre;
				primeNumber = currNumber;
				primeGenre = currGenre;
			} else if (secNumber < currNumber)
            {
				secNumber = currNumber;
				secGenre = currGenre;
			}
		}
		List<String> primAndSecGenre = new List<String>();
		primAndSecGenre.add(primeGenre);
		primAndSecGenre.add(secGenre);
		return primAndSecGenre;
	}

    public static  List<Mix__c> getAppropriateMix(List<Track__c> tracks)
    {
        Set<Id> mixID = new Set<Id>();
        for (Track__c track : tracks)
        {
            mixID.add(track.Mix__c);
        }
        return [SELECT  Name, Primary_Genre__c, Secondary_Genre__c,
         (SELECT Name, Song__c FROM  Tracks__r) FROM  Mix__c WHERE id in :mixID];

    }

	public static void updSongBeforeMixDel(List<Mix__c> oldValues)
    {
		List<Track__c> relatedTracks = TrackService.getRelatedTrack(oldValues);
		TrackService.updTrCountAfterDel(relatedTracks);
	}

	public static void  updSongAfterUndel(List<Mix__c> newValues)
    {
		List<Track__c> relatedTracks = TrackService.getRelatedTrack(newValues);
		TrackService.updTrCountAfterIns(relatedTracks);
	}

}