unpackaged/objects/Song__c.object
<CustomObject>
    <description>An instance of a song.</description>
    <fields>
        <fullName>Genre__c</fullName>
        <description>Genre of the song.</description>
        <label>Genre</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rock</fullName>
                </value>
                <value>
                    <fullName>Rap</fullName>
                </value>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Indy</fullName>
                </value>
                <value>
                    <fullName>Jazz</fullName>
                </value>
                <value>
                    <fullName>Latin</fullName>
                </value>
                <value>
                    <fullName>Electronic</fullName>
                </value>
                <value>
                    <fullName>Folk</fullName>
                </value>
                <value>
                    <fullName>Pop</fullName>
                </value>
                <value>
                    <fullName>Hip hop</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Length_m__c</fullName>
        <description>Length of the song in minutes.</description>
        <label>Length</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Track_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of times a song is used as a track.</description>
        <label>Track Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Track_Licenses__c</fullName>
        <label>Track Licenses</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/SongService.cls
/**
 * Created by HP on 22.11.2017.
 */
public class SongService
{
    public static Map<Id, Song__c> getAppropriateSongs(List<Track__c> tracks)
    {
        Set <Id> usedSongId = new Set <Id>();
        for (Track__c track : tracks)
        {
            usedSongId.add(track.Song__c);
        }
        Map <Id, Song__c> appropriateSongs = new Map <Id, Song__c> (
                [SELECT id, Track_Count__c, Track_Licenses__c,Genre__c
                 FROM Song__c
                 WHERE Id in :usedSongId ]);
        return appropriateSongs;
    }
    
	public static List<Song__c> getRelatedSongs(List<Track__c> tracks)
		{
			Set <Id> usedSongId = new Set <Id>();
			for (Track__c track : tracks)
            {
					usedSongId.add(track.Song__c);
			}
			return[
				SELECT id, Track_Count__c, Track_Licenses__c, Genre__c, Name, Length_m__c
				FROM Song__c
				WHERE Id in :usedSongId ];
		}
}